### ISSUE TITLE
Does the pdi-git-plugin-1.1.0 plugin work with Azure DevOps?

### ISSUE THREAD

**Issue by rbortolini** [HiromuHota/pdi-git-plugin#38]
Does the pdi-git-plugin-1.1.0 plugin work with Azure DevOps? When I'm going to do a push he asks me for the username and password, when I inform my azure username and password nothing happens and asks for the username and password again? Is there a place where I can see a log of what is happening?

**Comment by HiromuHota** [comment]
> nothing happens and asks for the username and password again?

This means "not authorized" error came back from the server.
https://github.com/HiromuHota/pdi-git-plugin/blob/master/src/main/java/org/pentaho/di/git/spoon/model/UIGit.java#L671
I realized that this is not user-friendly because user has no idea why they are asked username/password again. I'll report an issue for this.

To your question:
> Does the pdi-git-plugin-1.1.0 plugin work with Azure DevOps?

I think it would work but you have to choose an auth method that pdi-git-plugin-1.1.0 can work with.
This plugin relies on JGit; and according to https://www.eclipse.org/forums/index.php/t/1100497/,
- Azure DevOps (formerly known as TFS) out of the box is configured only for NTLM authentication over HTTP.
- JGit does not do NTLM, and we have no plans to add support for it.

As suggested by the above url, try SSH.
Another suggestion is to use "Personal Access Token" indicated at https://developercommunity.visualstudio.com/content/problem/626405/jgit-fails-to-authenticate-with-tfs-2013-using-ntl.html.

Hope this helps.

**Comment by theeagle-code** [comment]
It works on my end. I simply used 'username + password' with the HTTPS-URL to connect to Azure DevOps. I will start testing tomorrow and post any behavior I come across while testing.
